# Generated by Django 4.1.1 on 2022-09-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=120, null=True)),
                ('mname', models.CharField(blank=True, max_length=120, null=True)),
                ('lname', models.CharField(blank=True, max_length=120, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('hospitalNo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('tribe', models.CharField(blank=True, max_length=120, null=True)),
                ('religion', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('patient_type', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='patient_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='patients_pic')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recordapp.patient_info')),
            ],
            options={
                'verbose_name_plural': 'patient_pic',
            },
        ),
    ]
